version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test